#+TITLE: Installing ARVADOS on Debian + GNU Guix

* Table of Contents                                                     :TOC:
 - [[#arvados-introduction-][Arvados Introduction ]]
 - [[#creating-a-debian-base-install-][Creating a Debian base install ]]
   - [[#choice-of-ext4-vs-xfs][Choice of ext4 vs XFS]]
   - [[#usb-based-server-installation][USB-based server installation]]

* Arvados Introduction 

With Arvados+GNU Guix we aim to crack two bioinformatics problems
at the same time (well, maybe even more, but these are our two main
problems):

1. Get rid of the central FS bottleneck
2. Create shareable pipelines

Arvados provides an answer to both, so in this document I'll try and
install Arvados on a small compute cluster. For this we will create a
number of GNU Guix packages.

* Creating a Debian base install 

The developers of Arvados use Debian Wheezy as a base install with an
XFS file system. Wheezy also misses out on the systemd split. So
Wheezy it is this time. Next time I do a cluster install it may be a
native GUIX distribution which probably will miss out on systemd
altogether (note I have systemd running on my desktop, I may change my
mind about servers at some point).

** Choice of ext4 vs XFS

In general, storing data on Linux should be
considered `unsafe'. Arvados, however, promises redundancy across
nodes, so we ought to be not too concerned with the underlying storage. 
Also, most of the jobs on this cluster will be transient.

Taking a look at these [[http://www.ilsistemista.net/index.php/virtualization/47-zfs-btrfs-xfs-ext4-and-lvm-with-kvm-a-storage-performance-comparison.html?limitstart=0][benchmarks]] I decided to go for ext4
initially. We use 1TB drives and ext4 is (still) the standard on
Linux. File writing and reading is mostly linear with Arvados FS and
most bioinformatics tools, so it won't make a huge difference. We can
try XFS later.

** USB-based server installation

*** Create bootable USB

Not all servers have a CDROM reader, so we need to create a bootable
[[https://wiki.debian.org/BootUsb][USB stick]] with a bootable partition. Debian instructions are
[[https://wiki.debian.org/BootUsb][here]]. Arvados requires amd64. So, basically, download an image (I
usually take CD1 only) and dd it to the USB drive (directly; not to a
partition):

: dd if=imagefile of=/dev/sdxx bs=4M; sync
:   679477248 bytes (679 MB) copied, 96.5819 s, 7.0 MB/s

Now it should boot and we can start server installs. This is a manual
job. An automated install will be interesting once we scale up, but
for now I only have to install some 10 machines and can't be bothered.

With one machine the USB and CDROM boot did not work. I used
debootstrap instead (the latter if you have a Debian login as root on
the machine already).

*** Install server

It needed a little bios nudging, but the installation was easy. 
I just select the defaults for a minimal install (select ssh 
server, not the full desktop). I installed machines

: fedor311: 8 x Intel 2.66Hz (6Mb, 5333bogomips), 32G RAM, 3TB
: fedor312: 8 x Intel 2.66Hz (6Mb, 5333bogomips), 32G RAM, 3TB
: fedor313: 8 x Intel 2.66Hz (6Mb, 5333bogomips), 32G RAM, 3TB
: fedor314: 8 x Intel 2.66Hz (6Mb, 5333bogomips), 32G RAM, 3TB
: fedor315: 8 x Intel 2.66Hz (6Mb, 5333bogomips), 32G RAM, 1TB
: fedor316: 8 x Intel 2.66Hz (6Mb, 5333bogomips), 32G RAM, 1TB
: fedor317: 8 x Intel 2.66Hz (6Mb, 5333bogomips), 32G RAM, 3TB
: fedor318: 8 x Intel 2.66Hz (6Mb, 5333bogomips), 32G RAM, 3TB
: dellR410: 8 x Intel 2.16Hz (2Mb, 4255bogomips), 24G RAM, 500GB

*** Partitioning the file system

The partitioning I opt for is usually sda1 root 10GB (for Debian),
sda2 8GB swap, sda3 root2 (for upgrades) and LVM for the rest. GUIX
will get a partition in there, as well as the home directories etc.
At installation time only the first two need to be defined.

: fdisk -l 
:   /dev/sda1   *        2048    20965375    10481664   83  Linux
:   /dev/sda2        20965376    36589567     7812096   82  Linux swap / Solaris

*** Automate, automate

When working on the 3rd server I decided I needed to automate things.
In the past I have worked with Cfengine and Chef (for example), but
those tools are not exactly what I want out of installation control
(though I like some of the philosophy in there). I'll write out what I
want and start simple (KISS). Arguably installation control can be
part of GNU Guix - and I know people are doing that (even for VMs) so
you can say deploy my-webserver with all configuration included.

So, as these things go I created the [[https://github.com/pjotrp/deploy][deploy tool]] which is used later
in the chain.

*** Docker

Docker should be latest (>1.5) and requires a Kernel upgrade.

**** Update the Linux kernel

To /etc/apt/sources.list add the line 

: deb http://http.debian.net/debian wheezy-backports main contrib non-free

and disable the CDROM ref in the file, while you are at it.

and

: apt-get update
: apt-cache search linux-image

will give the kernel to install, and

: apt-get install -t wheezy-backports linux-image-amd64 linux-headers-amd64

will install the kernel + headers and update grub2 (boot).

At this stage it probably makes sense to add a few more packages

#+begin_src sh
apt-get install -t wheezy-backports linux-image-amd64 \
        linux-headers-amd64 lvm2 ssh vim pigz bzip2 screen unzip  \
        sudo locales lynx mc rsync ncurses-bin \
        tzdata htop iftop gnupg \
        tree psmisc ntpdate pciutils screen
# (downloads 316Mb and answer two stupid questions, doh!)
locale-gen en_US.UTF-8 en_GB.UTF-8 nl_NL.UTF-8
# dpkg-reconfigure locales
#+end_src

Arguably the last step is not needed, Guix comes with its own locale
support. Make sure ssh still works after

#+begin_src sh
/etc/init.d/ssh reload
#+end_src sh

And test kernel reboot and ssh login before moving the box to a remote
location (no kiddin').

At this point we have an installed system. It takes about 15 minutes
of working time assuming the hardware behaves (it is worth checking
BIOS settings, at least check what the machine should do on power
failure).

From this point on the installation should be [[https://github.com/pjotrp/deploy/blob/master/doc/design.org][automated]]. For
development and testing of automation I use a KVM virtual machine as
described [[https://github.com/pjotrp/cloudbiolinux/blob/master/doc/linux_kvm.md][here]].

*** Post install

After logging in for the first time I create an arvados user and
disable root ssh

: PermitRootLogin no
: PasswordAuthentication yes

followed by setting stronger passwords for root and the user.
PasswordAutenthication should be disabled later.

*** Check

: apt-get install firmware-linux

