* Devroom name.

GNU Guile — the official extension language for the GNU Project

* Devroom description:

GNU Guile is the preferred extension system for the GNU Project which
features an implementation of the Scheme programming language, a
dialect of Lisp with a mature community. Guile 2.0, released in 2011,
was a major milestone with a new compiler infrastructure, a virtual
machine implementation, a switch to the Boehm-Demers-Weiser garbage
collector, many improvements to the Guile Scheme language itself, and
other major changes which will be complemented by the forthcoming
Guile 2.2 release.

The GNU Guile programming language is dynamically typed and
multi-paradigm.  Whilst there has been a recent increased interest in
functional approaches using Guile, object-oriented programming using
GOOPs (a CLOS-like object system), logic programming, and system
scripting are all options too.  As a language it is very suited to
meta-programming and has a powerful macro-system which allows users to
change the language on the fly.

The use of GNU Guile is growing and it used in a number of
applications, e.g., GNU Lilypond, Gnucash.  Amongst the important
applications currently written in Guile we have GNU Guix, a functional
software deployment manager for the GNU Project (and beyond) which
also underpins GuixSD a new functional GNU\Linux Distribution. GNU
Guix distinguishes itself by creating 100% reproducibly software
installations generated by a hackable system.  GNU Guix is a young
rapidly growing project with 40+ contributors, an estimated 175K lines
of source code whereof 70% is GNU Guile. Other noteworthy GNU Guile
applications include dmd, an init system and replacement for systemd,
mcron a cron-compatible task scheduler and two web frameworks (Haunt
and Artanis). A more exhaustive list can be found at
https://en.wikipedia.org/wiki/GNU_Guile.  The language also features a
growing set of bindings and libraries (ssh, json, sdl, opengl, cairo,
gtk, redis, sql, etc.).

The devroom will provide at least the following content with a focus
on software development:

- An introduction to GNU Guile
- Guile Next: Latest developments in GNU Guile
- Guile programming:
  + functors and monads in Guile
  + composable continuations in Guile
  + posix programming in Guile and the FFI
- Web frameworks with GNU Guile
- GNU Guix:
  + Latest GNU Guix developments
  + GNU/Hurd support in Guix
  + Python and Ruby support in GNU Guix
  + Adding reproducible bioinformatics pipelines to Guix
- Guile and the network:
  + Software distribution using Gnunet
  + Paving a path to greater network freedom using Guix and Guile
- The Guile community we could have (Or: solving Worse is More
  Accessible)
  
An complete list of currently considered talks can be found at
https://libreplanet.org/wiki/Group:Guix/TalkProposals.

The purpose of the dev room is to present latest developments in Guile
itself, to share exciting news about, and demo applications using Guile,
to provide a space to meet with fellow hackers and enthusiasts, and to
grow the Guile community.

* Related URLs

  - GNU Project: http://www.gnu.org
  - GNU Guile: https://www.gnu.org/software/guile/
  - GNU Guix: http://www.gnu.org/software/guix

* Why should FOSDEM accept this proposal?

GNU Guile is a core component of the successful and long running GNU
project, and today the language is being discovered by a new
generation of programmers.  From experience we know that language
tracks are popular at FOSDEM.

Even though aspects of this devroom track may overlap with other
language and software deployment tracks, we believe a more in-depth
hard-core language discussion is warranted for the GNU Guile language
which will attract core developers and freshly interested developers
(perhaps working on GNU Guix today). Also Ludovic Courtès has given
talks at FOSDEM before on GNU Guix in the Linux distributions track
which were popular and well received and a devroom would be a
continuation on that interest. This would be the first opportunity for
GNU Guile related projects world-wide to meet at FOSDEM.  We will also
invite speakers from other projects that are more loosely coupled to
the Guile environment (e.g. projects that use Guile purely as an
extension language, such as Lilypond).

In short, having this devroom will allow us to dig deeper into the
details of language design and reproducible builds in particular,
whilst giving back to the free software community as a whole.
    
* Devroom organisers

  - Ludovic Courtès (ludo@gnu.org) - GNU Guile project leader
  - Ricardo Wurmus (ricardo.wurmus@mdc-berlin.de)
  - Pjotr Prins (pjotr.public445@thebird.nl)
  - Alex Sassmannshausen (alex.sassmannshausen@gmail.com)
