* Devroom name:

GNU Guile — the official extension language for the GNU Project

* Devroom description:

The [[https://www.gnu.org/software/guile/][GNU Guile]] programming language is dynamically typed and
multi-paradigm.  Guile allows for functional approaches,
object-oriented programming using GOOPs (a CLOS-like object system),
logic programming, and system scripting.  Guile is suited to
meta-programming and has a powerful macro-system which allows users to
change the language on the fly.  Guile features a growing set of
bindings and libraries for libssh, json, sdl, opengl, cairo, gtk,
redis, SQL, etc.

GNU Guile is the preferred extension system for the GNU Project which
features an implementation of the Scheme programming language, a
dialect of Lisp with a mature community. Guile 2.0 (2011) was a major
milestone with a new compiler infrastructure, a virtual machine
implementation, a switch to the Boehm-Demers-Weiser garbage collector,
many improvements to the Guile Scheme language itself.  Other major
changes, including performance improvements demonstrated at FOSDEM,
will be in the next 2.2 release.

The use of GNU Guile is growing.  Amongst the current
applications written in Guile, there are OA, a new 3D CAD engine;
Scribolo, Artanis and haunt, (web) templating engines; Sly, a gaming
engine; and (of course) GNU Guix, a functional software deployment
manager for the GNU Project which also underpins GuixSD a new
functional GNU/Linux Distribution.

GNU Guix is a young rapidly growing project that distinguishes itself
by creating 100% reproducible software installations generated by a
hackable system. It has grown to approx. 200K lines of source code
whereof 180K lines are GNU Guile.  This year a lot of attention has
gone into distributed deployment, security and support for software
developers using Guile (of course), but also Java, Clojure, Perl,
Ruby, Python, Haskell, GO, D, Erlang, and Elixir.

Other noteworthy GNU Guile applications include GNU Lilypond, Gnucash,
shepherd (previously named dmd) which is an init system and
replacement for systemd; and mcron a cron-compatible task scheduler.
More GNU Guile projects can be found at
https://en.wikipedia.org/wiki/GNU_Guile and
https://www.gnu.org/software/guile/libraries/.

The devroom will provide at least the following content with a focus
on software development:

- An introduction to GNU Guile
- Guile Next: Latest developments in GNU Guile
- Guile programming and optimizations
- Web frameworks with GNU Guile
- Shepherd the systemd replacement
- GNU Guix:
  + Latest GNU Guix developments
  + GNU/Hurd support in Guix
  + Programming language support in GNU Guix
- Guile and the network:
  + Software distribution using Gnunet
  + Paving a path to greater network freedom using Guix and Guile
- The Guile community
  + Freedom can be expressed in multiple ways
  + Encouraging and mentoring newbies; encourage diversity
  + Tutorials and documentation

A complete list of currently considered talks can be found at
https://libreplanet.org/wiki/Group:Guix/TalkProposals.

The purpose of the dev room is to present latest developments in Guile
itself, to share exciting news about, and demo applications using Guile,
to provide a space to meet with fellow hackers and enthusiasts, and to
grow the Guile community.

* Related URLs

  - GNU Project: http://www.gnu.org
  - GNU Guile: https://www.gnu.org/software/guile/
  - GNU Guile libs: https://www.gnu.org/software/guile/libraries/
  - GNU Guix: http://www.gnu.org/software/guix

* Why should FOSDEM accept this proposal?

GNU Guile is a core component of the successful and long running GNU
project, and today the fresh Lisp language is being discovered by a
new generation of programmers.  Last year we had our first half day
Guile devroom at FOSDEM and it was a great success: the devroom was
full for every talk!  FOSDEM gave a great impulse by getting
developers together.  Together with the LUA devroom we overlapped a
session where we discussed the future of small languages (we are
interested in sharing the devroom with LUA again).

This would be the second opportunity for GNU Guile related projects
world-wide to meet at FOSDEM.  Similar to last year, we will invite
speakers from other projects that are loosely coupled to the Guile
environment (e.g. projects that use Guile purely as an extension
language, such as gdb and Lilypond).

In short, having this devroom will allow us to dig deeper into the
details of language design and reproducible software in particular,
whilst giving back to the free software community as a whole.

* Devroom organisers

  - Ludovic Courtès (ludo@xxx) - GNU Guile project leader
  - Ricardo Wurmus (ricardo.wurmus@xxx)
  - Pjotr Prins (pjotr.public445@xxx)
  - Alex Sassmannshausen (alex.sassmanns@xxx)
  - Tobias Geerinckx-Rice <me@xxx>
  - Manolis Ragkousis <manolis837@xxx>
